services:
  - type: static
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend
    envVars:
      - key: API_BASE_URL
        value: https://co2-logger.onrender.com/
